


//BEGIN_USER_SECTION_BEFORE_MASTER_INCLUDE

//END_USER_SECTION_BEFORE_MASTER_INCLUDE


#include "log4cxx.h"

//BEGIN_USER_SECTION_AFTER_MASTER_INCLUDE

//END_USER_SECTION_AFTER_MASTER_INCLUDE


log4cxx::LoggerPtr log4cxx::Logger::getRootLogger()
{//BEGIN_117ecd8f638329bb18cd3551e25a3f1d
    LoggerPtr ret;
    //TODO: getRootLogger()
    return ret;
}//END_117ecd8f638329bb18cd3551e25a3f1d


//BEGIN_USER_SECTION_AFTER_GENERATED_CODE

//END_USER_SECTION_AFTER_GENERATED_CODE